[package]
name = "to_sql"
version = "0.1.0"
authors = ["Alex Angelini <alex.louis.angelini@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.15"
env_logger = "0.8.1"
itertools = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.0"
regex = "1"
rust_decimal = "1.8.1"
